title: Mon site
titlecct: Contact
titleport: Portfolio
author: Christophe Delahaye
desc: Site en Jekyll
htitle: Bienvenue sur ce site Jekyll, c'est excellent
btitle: Bienvenue sur ce blog Jekyll, je le sens moyen